### PR TITLE
Implemented prerequisites feature

### PR DESCRIPTION
**Pull request by johannesostner**

### CODE REVIEW

**Comment by svenhertle** [comment]
I'm reviewing the change at the moment. Whats the use case of having an internal and separate public name for prerequisites? Would one name be enough?
Thank you!

**Comment by johannesostner** [comment]
The idea was to have one name for a prerequisite that might not be suited to show to the public (like "speaks English"), and one public name that can be shown in the registration form (like "I speak English").

This was proposed by @Tomatower, maybe he has an even better use case. Otherwise, I think we could remove this feature as well. 
Since the internal name is not really used anywhere ("Helpers can specify some prerequisites at registration" is not implemented yet), this should be pretty easy.

**Comment by Tomatower** [comment]
For completeness:

As @johannesostner said. 
Internally I want to have short names, that the team understands.
Externally I might want to have a longer and more descriptive name, in order to avoid possible confusion.

**Comment by svenhertle** [comment]
Ok, currently we have one name in English and German. So this is the internal name.
When we add the prerequisites to the public registration, we can simply add another name again.

**Pull request merged**
