### PR TITLE
implemented fuzzy matching for helper search

### LINKED ISSUE #48: use fuzzy-matching when searching for a helper
proper databases understand fuzzy-matching, so when you search for a helpers name you can do some typos and still find the person (meyer vs maier vs meier vs mayr vs mayer)

References:

**pgsql:** https://www.postgresql.org/docs/current/fuzzystrmatch.html#id-1.11.7.24.6
**mysql:** only the hacky-way: https://lucidar.me/en/web-dev/levenshtein-distance-in-mysql/ and https://stackoverflow.com/questions/13909885/how-to-add-levenshtein-function-in-mysql
**sqlite:** some kind of support: https://www.sqlite.org/spellfix1.html and https://stackoverflow.com/questions/49779281/string-similarity-with-python-sqlite-levenshtein-distance-edit-distance/49815419#49815419
**django:** https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/lookups/#trigram-similarity does not seem to be suited for single-word-searches

but who in their right mind would run it on something else than postgres?
oh wait. stustaculum does.
and development does.

### PR DESCRIPTION
**Pull request by Tomatower**
Seems to work fine. The threshold needs tuning on a bigger database, I think values between 0.2 on the broad-matching side and 0.5 on the wide-matching side are reasonable.

The migration to install the required postgres extension does not work unless the database user has full access to the database, which might not be intended, so there has to be some better way.

closes #48

### CODE REVIEW

**Comment by Tomatower** [comment]
Likelihood has now min `0.3`, seems better now, ready for merge.

**Comment by svenhertle** [comment]
I found a nice workaround for the extension installation: we can check in `settings.py` if the extension is installed and otherwise disable the fuzzy search. I will add the `CREATE EXTENSION pg_trgm;` to the documentation. Will change this during merge.

**Comment by Tomatower** [comment]
If you include it into the settings, maybe also add it to helfertool.yaml for global disabling.
Maybe some event does not like the option to simply grab a list of a lot of helpers without knowing their exact name... 

Performancewise, I have tested fuzzy matching with a pool of 4000 helpers in one event and did not encounter any major performance limitations in the fuzzy search on lowest performance machine.

**Comment by Tomatower** [comment]
Also please remove the debugs output where the matching quality for first and surname is displayed, this is might be confusing to an enduser

**Comment by svenhertle** [comment]
Merged in 769b55c27620e0783eb2c2425b7b8ee5ccca52b1
Thank you!

**Pull request closed without merging**
